# Pandas Merge vs Concatenate

In [61]:
import pandas as pd
set1 = pd.DataFrame({"A": [1,2,3,4,5],"B": [21,33,22,55,66]})

set2 = pd.DataFrame({"A":[1,2,3,4,9],"Z":[45,66,77,88,0]})

pd.merge(set1,set2,on="A")

   A   B   Z
0  1  21  45
1  2  33  66
2  3  22  77
3  4  55  88

# Merge supports four types of joins

 * 1 . Left

In [62]:
pd.merge(set1,set2,how="left")

   A   B     Z
0  1  21  45.0
1  2  33  66.0
2  3  22  77.0
3  4  55  88.0
4  5  66   NaN

* 2 . Right

In [50]:
pd.merge(set1,set2,how="right")

   A     B   Z
0  1  21.0  45
1  2  33.0  66
2  3  22.0  77
3  4  55.0  88
4  9   NaN   0

* 3 . Outer

In [51]:
pd.merge(set1,set2,how="outer")

   A     B     Z
0  1  21.0  45.0
1  2  33.0  66.0
2  3  22.0  77.0
3  4  55.0  88.0
4  5  66.0   NaN
5  9   NaN   0.0

* 4 . Inner

In [52]:
pd.merge(set1,set2,how="inner")

   A   B   Z
0  1  21  45
1  2  33  66
2  3  22  77
3  4  55  88

In [53]:
pd.merge(set1,set2,how="outer",indicator=True)

   A     B     Z      _merge
0  1  21.0  45.0        both
1  2  33.0  66.0        both
2  3  22.0  77.0        both
3  4  55.0  88.0        both
4  5  66.0   NaN   left_only
5  9   NaN   0.0  right_only

# Merge Using Indexes

In [63]:
 pd.merge(set1,set2,how="outer",left_index=True,right_index=True)

   A_x   B  A_y   Z
0    1  21    1  45
1    2  33    2  66
2    3  22    3  77
3    4  55    4  88
4    5  66    9   0

# Handling Duplicate Column Names with Suffixes

In [55]:
 pd.merge(set1,set2,how="outer",left_index=True,right_index=True,suffixes=("Number","Roll"))

   ANumber   B  ARoll   Z
0        1  21      1  45
1        2  33      2  66
2        3  22      3  77
3        4  55      4  88
4        5  66      9   0

# Concatenate

In [56]:
set1 = pd.DataFrame({"A": [1,2,3,4,5],"B": [21,33,22,55,66]})

set2 = pd.DataFrame({"i":[1,2,3,4,9],"Z":[45,66,77,88,0]})

pd.concat([set1,set2],axis=1)

   A   B  i   Z
0  1  21  1  45
1  2  33  2  66
2  3  22  3  77
3  4  55  4  88
4  5  66  9   0

In [57]:
set1 = pd.DataFrame({"A": [1,2,3,4,5],"B": [21,33,22,55,66]})

set2 = pd.DataFrame({"i":[1,2,3,66,77],"Z":[33,2,3,4,1]})

pd.concat([set1,set2],axis=1,join="inner")

   A   B   i   Z
0  1  21   1  33
1  2  33   2   2
2  3  22   3   3
3  4  55  66   4
4  5  66  77   1